/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tarea5;

/**
 *
 * @author Xavier
 */
public class Calculadora extends javax.swing.JFrame {

    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        boton1 = new javax.swing.JButton();
        boton2 = new javax.swing.JButton();
        boton3 = new javax.swing.JButton();
        botonSuma = new javax.swing.JButton();
        boton4 = new javax.swing.JButton();
        boton5 = new javax.swing.JButton();
        boton6 = new javax.swing.JButton();
        botonResta = new javax.swing.JButton();
        boton7 = new javax.swing.JButton();
        boton8 = new javax.swing.JButton();
        boton9 = new javax.swing.JButton();
        botonMulti = new javax.swing.JButton();
        boton0 = new javax.swing.JButton();
        botonDeci = new javax.swing.JButton();
        botonIgual = new javax.swing.JButton();
        botonDiv = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        botonSalir = new javax.swing.JButton();
        botonLimpiar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        pantalla = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");

        jPanel1.setLayout(new java.awt.GridBagLayout());

        boton1.setText("1");
        boton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boton1.setMaximumSize(new java.awt.Dimension(41, 39));
        boton1.setMinimumSize(new java.awt.Dimension(41, 39));
        boton1.setPreferredSize(new java.awt.Dimension(41, 24));
        boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton1ActionPerformed(evt);
            }
        });
        jPanel1.add(boton1, new java.awt.GridBagConstraints());

        boton2.setText("2");
        boton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boton2.setMaximumSize(new java.awt.Dimension(41, 39));
        boton2.setMinimumSize(new java.awt.Dimension(41, 39));
        boton2.setPreferredSize(new java.awt.Dimension(41, 24));
        boton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton2ActionPerformed(evt);
            }
        });
        jPanel1.add(boton2, new java.awt.GridBagConstraints());

        boton3.setText("3");
        boton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boton3.setMaximumSize(new java.awt.Dimension(41, 39));
        boton3.setMinimumSize(new java.awt.Dimension(41, 39));
        boton3.setPreferredSize(new java.awt.Dimension(41, 24));
        boton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton3ActionPerformed(evt);
            }
        });
        jPanel1.add(boton3, new java.awt.GridBagConstraints());

        botonSuma.setText("+");
        botonSuma.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonSuma.setMaximumSize(new java.awt.Dimension(41, 39));
        botonSuma.setMinimumSize(new java.awt.Dimension(41, 39));
        botonSuma.setPreferredSize(new java.awt.Dimension(41, 24));
        botonSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSumaActionPerformed(evt);
            }
        });
        jPanel1.add(botonSuma, new java.awt.GridBagConstraints());

        boton4.setText("4");
        boton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boton4.setMaximumSize(new java.awt.Dimension(41, 39));
        boton4.setMinimumSize(new java.awt.Dimension(41, 39));
        boton4.setPreferredSize(new java.awt.Dimension(41, 24));
        boton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        jPanel1.add(boton4, gridBagConstraints);

        boton5.setText("5");
        boton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boton5.setMaximumSize(new java.awt.Dimension(41, 39));
        boton5.setMinimumSize(new java.awt.Dimension(41, 39));
        boton5.setPreferredSize(new java.awt.Dimension(41, 24));
        boton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton5ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        jPanel1.add(boton5, gridBagConstraints);

        boton6.setText("6");
        boton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boton6.setMaximumSize(new java.awt.Dimension(41, 39));
        boton6.setMinimumSize(new java.awt.Dimension(41, 39));
        boton6.setPreferredSize(new java.awt.Dimension(41, 24));
        boton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton6ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        jPanel1.add(boton6, gridBagConstraints);

        botonResta.setText("-");
        botonResta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonResta.setMaximumSize(new java.awt.Dimension(41, 39));
        botonResta.setMinimumSize(new java.awt.Dimension(41, 39));
        botonResta.setPreferredSize(new java.awt.Dimension(41, 24));
        botonResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRestaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        jPanel1.add(botonResta, gridBagConstraints);

        boton7.setText("7");
        boton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boton7.setMaximumSize(new java.awt.Dimension(41, 39));
        boton7.setMinimumSize(new java.awt.Dimension(41, 39));
        boton7.setPreferredSize(new java.awt.Dimension(41, 24));
        boton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton7ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        jPanel1.add(boton7, gridBagConstraints);

        boton8.setText("8");
        boton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boton8.setMaximumSize(new java.awt.Dimension(41, 39));
        boton8.setMinimumSize(new java.awt.Dimension(41, 39));
        boton8.setPreferredSize(new java.awt.Dimension(41, 24));
        boton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton8ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        jPanel1.add(boton8, gridBagConstraints);

        boton9.setText("9");
        boton9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boton9.setMaximumSize(new java.awt.Dimension(41, 39));
        boton9.setMinimumSize(new java.awt.Dimension(41, 39));
        boton9.setPreferredSize(new java.awt.Dimension(41, 24));
        boton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton9ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        jPanel1.add(boton9, gridBagConstraints);

        botonMulti.setText("*");
        botonMulti.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonMulti.setMaximumSize(new java.awt.Dimension(41, 39));
        botonMulti.setMinimumSize(new java.awt.Dimension(41, 39));
        botonMulti.setPreferredSize(new java.awt.Dimension(41, 24));
        botonMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMultiActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        jPanel1.add(botonMulti, gridBagConstraints);

        boton0.setText("0");
        boton0.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boton0.setMaximumSize(new java.awt.Dimension(41, 39));
        boton0.setMinimumSize(new java.awt.Dimension(41, 39));
        boton0.setPreferredSize(new java.awt.Dimension(41, 24));
        boton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton0ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        jPanel1.add(boton0, gridBagConstraints);

        botonDeci.setText(".");
        botonDeci.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonDeci.setMaximumSize(new java.awt.Dimension(41, 39));
        botonDeci.setMinimumSize(new java.awt.Dimension(41, 39));
        botonDeci.setPreferredSize(new java.awt.Dimension(41, 24));
        botonDeci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDeciActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        jPanel1.add(botonDeci, gridBagConstraints);

        botonIgual.setText("=");
        botonIgual.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonIgual.setMaximumSize(new java.awt.Dimension(41, 39));
        botonIgual.setMinimumSize(new java.awt.Dimension(41, 39));
        botonIgual.setPreferredSize(new java.awt.Dimension(41, 24));
        botonIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIgualActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        jPanel1.add(botonIgual, gridBagConstraints);

        botonDiv.setText("/");
        botonDiv.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonDiv.setMaximumSize(new java.awt.Dimension(41, 39));
        botonDiv.setMinimumSize(new java.awt.Dimension(41, 39));
        botonDiv.setPreferredSize(new java.awt.Dimension(41, 24));
        botonDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDivActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        jPanel1.add(botonDiv, gridBagConstraints);

        jPanel3.setPreferredSize(new java.awt.Dimension(164, 71));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        botonSalir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonSalir.setText("OFF");
        botonSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonSalir.setMaximumSize(new java.awt.Dimension(65, 23));
        botonSalir.setMinimumSize(new java.awt.Dimension(65, 23));
        botonSalir.setPreferredSize(new java.awt.Dimension(65, 23));
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 3;
        jPanel3.add(botonSalir, gridBagConstraints);

        botonLimpiar.setText("CLEAR");
        botonLimpiar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLimpiarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        jPanel3.add(botonLimpiar, gridBagConstraints);

        pantalla.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        pantalla.setEnabled(false);
        pantalla.setPreferredSize(new java.awt.Dimension(164, 30));
        jPanel4.add(pantalla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIgualActionPerformed
        // TODO add your handling code here:
        if(Metodos.checkOperandos(pantalla.getText())){
            pantalla.setText(Metodos.operacion(pantalla.getText()));
        }
    }//GEN-LAST:event_botonIgualActionPerformed

    private void boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton1ActionPerformed
        // TODO add your handling code here:
        pantalla.setText(pantalla.getText() + "1");
    }//GEN-LAST:event_boton1ActionPerformed

    private void boton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton2ActionPerformed
        // TODO add your handling code here:
        pantalla.setText(pantalla.getText() + "2");
    }//GEN-LAST:event_boton2ActionPerformed

    private void boton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton3ActionPerformed
        // TODO add your handling code here:
        pantalla.setText(pantalla.getText() + "3");
    }//GEN-LAST:event_boton3ActionPerformed

    private void boton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton4ActionPerformed
        // TODO add your handling code here:
        pantalla.setText(pantalla.getText() + "4");
    }//GEN-LAST:event_boton4ActionPerformed

    private void boton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton5ActionPerformed
        // TODO add your handling code here:
        pantalla.setText(pantalla.getText() + "5");
    }//GEN-LAST:event_boton5ActionPerformed

    private void boton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton6ActionPerformed
        // TODO add your handling code here:
        pantalla.setText(pantalla.getText() + "6");
    }//GEN-LAST:event_boton6ActionPerformed

    private void boton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton7ActionPerformed
        // TODO add your handling code here:
        pantalla.setText(pantalla.getText() + "7");
    }//GEN-LAST:event_boton7ActionPerformed

    private void boton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton8ActionPerformed
        // TODO add your handling code here:
        pantalla.setText(pantalla.getText() + "8");
    }//GEN-LAST:event_boton8ActionPerformed

    private void boton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton9ActionPerformed
        // TODO add your handling code here:
        pantalla.setText(pantalla.getText() + "9");
    }//GEN-LAST:event_boton9ActionPerformed

    private void boton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton0ActionPerformed
        // TODO add your handling code here:
        pantalla.setText(pantalla.getText() + "0");
    }//GEN-LAST:event_boton0ActionPerformed

    private void botonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLimpiarActionPerformed
        // TODO add your handling code here:
        pantalla.setText("");
        botonDeci.setEnabled(true);
    }//GEN-LAST:event_botonLimpiarActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSumaActionPerformed
        // TODO add your handling code here:
        pantalla.setText(pantalla.getText() + "+");
        botonDeci.setEnabled(true);
    }//GEN-LAST:event_botonSumaActionPerformed

    private void botonRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRestaActionPerformed
        // TODO add your handling code here:
        pantalla.setText(pantalla.getText() + "-");
        botonDeci.setEnabled(true);
    }//GEN-LAST:event_botonRestaActionPerformed

    private void botonMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMultiActionPerformed
        // TODO add your handling code here:
        pantalla.setText(pantalla.getText() + "*");
        botonDeci.setEnabled(true);
    }//GEN-LAST:event_botonMultiActionPerformed

    private void botonDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDivActionPerformed
        // TODO add your handling code here:
        pantalla.setText(pantalla.getText() + "/");
        botonDeci.setEnabled(true);
    }//GEN-LAST:event_botonDivActionPerformed

    private void botonDeciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDeciActionPerformed
        // TODO add your handling code here:
        pantalla.setText(pantalla.getText() + ".");
        botonDeci.setEnabled(false);
    }//GEN-LAST:event_botonDeciActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton0;
    private javax.swing.JButton boton1;
    private javax.swing.JButton boton2;
    private javax.swing.JButton boton3;
    private javax.swing.JButton boton4;
    private javax.swing.JButton boton5;
    private javax.swing.JButton boton6;
    private javax.swing.JButton boton7;
    private javax.swing.JButton boton8;
    private javax.swing.JButton boton9;
    private javax.swing.JButton botonDeci;
    private javax.swing.JButton botonDiv;
    private javax.swing.JButton botonIgual;
    private javax.swing.JButton botonLimpiar;
    private javax.swing.JButton botonMulti;
    private javax.swing.JButton botonResta;
    private javax.swing.JButton botonSalir;
    private javax.swing.JButton botonSuma;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField pantalla;
    // End of variables declaration//GEN-END:variables
}
